### ISSUE TITLE
Error compiling fortran code

### ISSUE THREAD

**Issue by ykiriscioglu** [manoharan-lab/holopy#275]
After setting up version 3.3 from GitHub, and compiling the fortran code on the lab computer, I ran into an ImportError:

`/Code/holopy/holopy/scattering/theory/tmatrix_f/S.so: undefined symbol: PyCObject_Type`

I didn't run into any errors setting up on my Mac, however. Is this related to the version of gfortran installed? If so, how should I proceed?

@ralex0  @vnmanoharan

**Comment by ykiriscioglu** [comment]
This is the complete error message:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-7198211aaff3> in <module>()
      2 
      3 import numpy as np
----> 4 import holopy as hp
      5 import cma
      6 import sys

~/Code/holopy/holopy/__init__.py in <module>()
     32 
     33 
---> 34 from holopy import core, scattering, fitting, inference
     35 from holopy.core import (load, save, load_image, save_image, show, test_display,
     36                                             detector_grid, detector_points)

~/Code/holopy/holopy/scattering/__init__.py in <module>()
     39 '''
     40 
---> 41 from holopy.scattering import scatterer, theory
     42 from holopy.scattering.scatterer import (Scatterer, Scatterers, Sphere,
     43     LayeredSphere, Spheres, RigidCluster, Ellipsoid, Capsule, Cylinder,

~/Code/holopy/holopy/scattering/theory/__init__.py in <module>()
     33 from holopy.scattering.theory.multisphere import Multisphere
     34 from holopy.scattering.theory.dda import DDA
---> 35 from holopy.scattering.theory.tmatrix import Tmatrix

~/Code/holopy/holopy/scattering/theory/tmatrix.py in <module>()
     30 from holopy.core.errors import DependencyMissing
     31 from holopy.scattering.theory.scatteringtheory import ScatteringTheory
---> 32 from holopy.scattering.theory.tmatrix_f.S import ampld
     33 try:
     34     from holopy.scattering.theory.mie_f import mieangfuncs

ImportError: /home/ykiriscioglu/Code/holopy/holopy/scattering/theory/tmatrix_f/S.so: undefined symbol: PyCObject_Type
```

**Comment by ralex0** [comment]
What version of python are you using? Can you post your environment?

**Comment by ykiriscioglu** [comment]
I'm using Python version 3.6.5, and I uploaded my environment here:
[https://anaconda.org/ykiriscioglu/base/files](url)

**Comment by ralex0** [comment]
Thanks, and what's the gfortran version and OS?

**Comment by ykiriscioglu** [comment]
GNU Fortran version 4.8.4
The OS is Ubuntu 14.04.5 LTS

**Comment by ralex0** [comment]
@briandleahy You have experienced a similar error right? Can you give your gfortran version and OS as well? 

I developed the extension using gcc 8.3.0 on Ubuntu 18.10  (Cosmic Cuttlefish)

**Comment by briandleahy** [comment]
The errors I got on my laptop were slightly different. Here they are:
```python
======================================================================
ERROR: The original [ampld.lpd.f]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/holopy/holopy/scattering/tests/test_tmatrix.py", line 93, in test_calc_scattering_matrix
    s = ampld(*list(params.values()))
S.error: (len(thet)>=nang) failed for 1st keyword nang: ampld:nang=65

======================================================================
ERROR: test_calc_scattering_matrix_multiple_angles (holopy.scattering.tests.test_tmatrix.TestTMatrix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/brian/holopy/holopy/scattering/tests/test_tmatrix.py", line 149, in test_calc_scattering_matrix_multiple_angles
    s = ampld(*list(params.values()))
S.error: (len(thet)>=nang) failed for 1st keyword nang: ampld:nang=65
```
That machine was

**Comment by briandleahy** [comment]
Regarding the errors on my machine -- I think it's an issue with the test. The test calls
```python
        s = ampld(*list(params.values()))
```
but params is a dict, so ```*list(params.values())``` does *not* return the same order each time, which means that when there are 15 parameters to the fortran code, some of them are bound to be out of order, and that will cause an error. That might make sense why I am having issues, but I don't think this is Yasemin's problem.

**Comment by ralex0** [comment]
@briandleahy Okay, I'll just make a PR making params an OrderedDict so it's python 3.5 compatible.

@ykiriscioglu I think your error is actually a compilation issue related to python 2 being in the path. (Based on googling the error) I'll investigate by trying to install on a lab computer.

**Comment by levbershadsky** [comment]
I am also having a problem compiling to fortran code, but in my case the package doesn't even install.
This is the error mesage:
```
/usr/bin/gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/holopy/scattering/theory/mie_f/uts_scsmfomodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/holopy/scattering/theory/mie_f/fortranobject.o build/temp.linux-x86_64-3.7/home/lev/Downloads/holopy/holopy/scattering/theory/mie_f/uts_scsmfo.o build/temp.linux-x86_64-3.7/home/lev/Downloads/holopy/holopy/scattering/third_party/SBESJY.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib -lgfortran -o /home/lev/Downloads/holopy/holopy/scattering/theory/mie_f/uts_scsmfo.cpython-37m-x86_64-linux-gnu.so
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
error: Command "/usr/bin/gfortran -Wall -g -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/holopy/scattering/theory/mie_f/uts_scsmfomodule.o build/temp.linux-x86_64-3.7/build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/holopy/scattering/theory/mie_f/fortranobject.o build/temp.linux-x86_64-3.7/home/lev/Downloads/holopy/holopy/scattering/theory/mie_f/uts_scsmfo.o build/temp.linux-x86_64-3.7/home/lev/Downloads/holopy/holopy/scattering/third_party/SBESJY.o -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib -L/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../lib -lgfortran -o /home/lev/Downloads/holopy/holopy/scattering/theory/mie_f/uts_scsmfo.cpython-37m-x86_64-linux-gnu.so" failed with exit status 1
```
This is the latest 3.3 branch with numpy `1.17.0`, `gcc (GCC) 9.1.0`, `gcc-fortran 9.1.0`.

The operating system is Arch Linux, kernel `5.2.5`.

**Comment by ralex0** [comment]
I have successful installed the 3.3 branch on a lab computer (Ubuntu 14.04.5 LTS, gcc version 5.5.0 20171010). Here are the steps I took from my profile (which was fresh and unconfigured previously):
1. [Install Miniconda](https://docs.conda.io/en/latest/miniconda.html)
2. Create a new environment with python 3.6. I ran `conda create -n holopy-install python=3.6`
3. Switch to my new environment "holopy-install"
3. Install holopy dependencies with `conda install -c conda-forge --only-deps holopy`
4. Cloned the 3.3 branch of holopy to my home directiory
5. Change to holopy directory, and install in develop mode: `pip install -e .`

That's it. It resulted in this environment for me: 
```
name: holopy-install
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py36_1
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - emcee=2.2.1=pyh24bf2e0_4
  - expat=2.2.5=he1b5a44_1003
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5netcdf=0.7.4=py_0
  - h5py=2.9.0=nompi_py36h513d04c_1104
  - hdf5=1.10.5=nompi_h3c11f04_1100
  - icu=58.2=hf484d3e_1000
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py36hc9558a2_0
  - libblas=3.8.0=11_openblas
  - libcblas=3.8.0=11_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=11_openblas
  - libopenblas=0.3.6=h6e990d7_6
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.0=py36h5429711_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.17.0=py36h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1c=h516909a_0
  - pandas=0.25.0=py36hb3f55d8_0
  - pcre=8.41=hf484d3e_1003
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.1.1=py36_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36hcca6a23_2
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py36h516909a_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=h7b6447c_5
  - scipy=1.3.1=py36h921218d_1
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.12.0=py36_1000
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py36h516909a_0
  - wheel=0.33.4=py36_0
  - xarray=0.12.3=py_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=h14c3975_1001
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.0=h3b9ef0a_0
prefix: /home/ralexander/Anaconda/envs/holopy-install
```

After installing few additional dependencies (`pip install nose cma schwimmbad`) I ran the test suite and everything passed.
