### ISSUE TITLE
Incorrect way of initializing xarray.DataArray

### ISSUE THREAD

**Issue by VasLem** [manoharan-lab/holopy#411]
This [line](https://github.com/manoharan-lab/holopy/blob/9d4b2e3f08146c0e387b03a78875d65edec88e61/holopy/scattering/imageformation.py#L145) updates the coords variable with a value that breaks the indexing of the DataArray.

The problem can easily be replicated by running the [tutorial](https://holopy.readthedocs.io/en/master/tutorial/calc_tutorial.html#a-simple-example) 

The error raised is:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\user\.conda\envs\triseq\lib\site-packages\xarray\core\dataarray.py", line 417, in __init__
    indexes, coords = _create_indexes_from_coords(coords)
  File "C:\Users\user\.conda\envs\triseq\lib\site-packages\xarray\core\merge.py", line 609, in _create_indexes_from_coords
    idx, idx_vars = create_default_index_implicit(variable, all_variables)
  File "C:\Users\user\.conda\envs\triseq\lib\site-packages\xarray\core\indexes.py", line 1061, in create_default_index_implicit
    raise ValueError(
ValueError: conflicting MultiIndex level / variable name(s):
x
y
z
```

**Comment by VasLem** [comment]
xarray version 0.21.1 seems compatible with the current code. Maybe it should be explicitly stated in the requirements.txt, until an update to the code is composed.

**Comment by emanuelevivoli** [comment]
same problem here
